### ISSUE TITLE
Not available for 32 bits

### ISSUE THREAD

**Issue by PERCE-NEIGE** [snapcrafters/s4a#1]
I can't install it on a 32 bits computer. 

What I did:
- I downloaded the .deb package, it won't install, but it doesn't tell me what are the dependencies that are missing.  
- I wrote "sudo snap install s4a" in terminal, it says that it's not stable for my architecture.

**Comment by merlijn-sebrechts** [comment]
What distro and version are you using? The last Ubuntu version that supported creating a new 32-bit installation was 16.04 afaik. It might be better to just switch to a 64-bit installation. Many programs stopped supporting 32-bit installations and the last Ubuntu LTS dropped support for 32-bit installations completely.

I can look into porting the snap to 32-bit, however, I'm not sure if that is really a good use of my time, given that very few people still use it and the number is only going down. The last regular Intel processor without support for 64-bit was created around 2006 as far as I know.

What processer is your computer using? All the Intel processors made in the last decade support both 32-bit and 64-bit, so it's possible that you can simply reinstall to a 64-bit installation; that will solve a lot of problems for you.

**Comment by PERCE-NEIGE** [comment]
Okay, I understand 32-bits is now a niche.
I didn't test 64, but I will.

I tried on several distro (Ubuntu LTS, etc), live sessions or not,
I have an Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz

**Comment by merlijn-sebrechts** [comment]
That CPU should _definitely_ be able to run 64-bits Ubuntu.

64-bit also has more/better security fixes for the meltdown and spectre-type vulnerabilities, so it's advised to use that if your computer supports it.

Let me know how it goes!
